name: usbmode-switch
version: '0.2' 
summary: usb-modeswitch packaged as snap
description: |
  usb-modeSwitch is (surprise!) a mode switching tool for controlling 'multi-mode' USB devices.

grade: stable
confinement: strict

parts:
  usb-modeswitch:
    plugin: make
    source: http://www.draisberghof.de/usb_modeswitch/usb-modeswitch-2.5.2.tar.bz2
    stage-packages:
      - libusb-1.0-0
      - libusb-1.0-0-dev
    build-packages:
      - pkg-config

  usb-modeswitch-data:
    plugin: make
    source: http://www.draisberghof.de/usb_modeswitch/usb-modeswitch-data-20170806.tar.bz2
    stage-packages:
      - libusb-1.0-0
      - libusb-1.0-0-dev
    build-packages:
      - pkg-config

apps:
  usb-modeswitch: # Default program
    command: usb_modeswitch
    plugs: [network-control, raw-usb]

  conf-huaweii: # Configures the Huaweii E3372 / E8372 LTE modem from storage mode to modem mode
    daemon: simple
    restart-condition: always
    command: usb_modeswitch -v 12d1 -p 1f01 -M '55534243123456780000000000000a11062000000000000100000000000000'
    plugs: [huaweii-modem, network-control, raw-usb]


plugs:
  huaweii-modem:
    interface: serial-port

# To Do: Strict confinement should be obtained
# This is how we want to use the slot in the gadget snap
# slots:
#   huaweii-modem:
#     interface: serial-port
#     path: /dev/serial-port-huaweii-modem
#     usb-vendor: 0x12d1
#     usb-product: 0x1f01